package com.management.risk.Exception;

public enum  Exceptions {
    THRESHOLD_EXCEPTION,
    NO_RISK_FOUND,
    NON_VALID_PARAMETER_YEAR,
    NON_VALID_PARAMETER_SIM,
    NON_VALID_PARAMETER_PROBA_DIV,
    NON_VALID_PARAMETER_CAPACITY,
    NO_FAULT_TREE_FOUND,
    USER_NOT_FOUND,
}
